version: '3.1'
services:
  db: # makes DB available. JDBC-URL: "jdbc:postgresql://localhost:15433/"
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: message_db_local
      POSTGRES_USER: msg # DB user
      POSTGRES_PASSWORD: msg # DB password
    ports:
      - 15433:5432 # bind to port 15432 on machine running docker (normally localhost)
