spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:15433/message_db_local?currentSchema=public # add database name to URL
    username: msg # DB user
    password: msg # DB password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migrations
    validateOnMigrate: false
logging:
  level:
    org.flywaydb: DEBUG

msg:
  jobs:
    message-schedule: "* * * 30 * *"

firebase:
  recepientToken:


jwt-security:
    secret:
    expiration-time: 3621
